;; Generated by repo-forge new --archetype rust-substrate-tool
;; Edit this file + run `repo-forge migrate .` to rewrite artifacts.

(defrepo ponte
  :description "Bridges LangChain OpenWiki into the pleme-io fleet: reads the target repo's typescape IR + zoekt hits as context, invokes OpenWiki unmodified as a subprocess, routes the result through the fleet's doc/compliance layers."
  :kind :rust-tool
  :visibility :private
  :binary "ponte"
;; archetype: rust-substrate-tool
;; bindings:
;;   name = "ponte"
;;   toolName = "ponte"
;;   description = "Bridges LangChain OpenWiki into the pleme-io fleet: reads the target repo's typescape IR + zoekt hits as context, invokes OpenWiki unmodified as a subprocess, routes the result through the fleet's doc/compliance layers."
)
